# Generated by Django 4.1.4 on 2023-01-02 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofileinfo',
            old_name='potfolio_site',
            new_name='profile_site',
        ),
    ]
